name: UNIVERSE_OS_DEV_BUILD

on:
  release:
    types: [created] # 表示在创建新的 Release 时触发
    
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: run.py
          onefile: true
          include-data-dir: core/html=core/html
          output-file: UNIVERSE_OS_DEV_${{ github.ref_name }}


      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: UNIVERSE_OS_DEV_${{ github.ref_name }}_${{ runner.os }}-Build
          path: |
            build/*.bin
